var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/platform/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__10~x.5a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0r~t0y5.js")
R.c("server/chunks/ssr/[root-of-the-server]__00z74jm._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_platform_page_actions_0h41at0.js")
R.m(78671)
module.exports=R.m(78671).exports
